// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-t6P4ctuIfq72EjQejLr2XQG2sZEnj8Q',
    appId: '1:1051226705322:web:9062e105b26354b17e2fd3',
    messagingSenderId: '1051226705322',
    projectId: 'getx-555d3',
    authDomain: 'getx-555d3.firebaseapp.com',
    storageBucket: 'getx-555d3.appspot.com',
    measurementId: 'G-H7L4ZD1CSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5pWifG9Y5-ryXU6deFD7RKaK_5z9877k',
    appId: '1:1051226705322:android:788997b437d560bc7e2fd3',
    messagingSenderId: '1051226705322',
    projectId: 'getx-555d3',
    storageBucket: 'getx-555d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPX4pMD35KgU7-jYqCb9Xw40pT5aQVIQs',
    appId: '1:1051226705322:ios:707407a557f612eb7e2fd3',
    messagingSenderId: '1051226705322',
    projectId: 'getx-555d3',
    storageBucket: 'getx-555d3.appspot.com',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPX4pMD35KgU7-jYqCb9Xw40pT5aQVIQs',
    appId: '1:1051226705322:ios:fc9d8738f03507b37e2fd3',
    messagingSenderId: '1051226705322',
    projectId: 'getx-555d3',
    storageBucket: 'getx-555d3.appspot.com',
    iosBundleId: 'com.example.getx.RunnerTests',
  );
}
